spring.datasource.url=jdbc:postgresql://localhost:5432/telegram_bot
spring.datasource.username=
spring.datasource.password=
telegram.bot.token=919746748:
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
