spring.datasource.url=jdbc:postgresql://localhost:5432/telegram_bot
spring.datasource.username=pavel
spring.datasource.password=21062006mMm
telegram.bot.token=919746748:AAGneWbpG1z0CyT6TZJ8cUOmBMSMQYGrNQk
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
